### ISSUE TITLE
Update unist-util-is

### ISSUE THREAD

**Issue by wooorm** [eush77/unist-util-remove#1]
Hi! 👋 

I was planning on updating this, but unist-util-is removed equality checks in favour of partial property checks (https://github.com/syntax-tree/unist-util-is/issues/1, I remember we talked about that issue, maybe on Gitter?)

Anyway, this project uses equality checks a lot (in tests and examples at least). So what should we do?

a) overwrite partial checks with a `type` (e.g., `remove(tree, {type: 'listItem'})`) as an equality tests?
b) expect people to pass in equality checks themselves (e.g., `remove(tree, n => n === someNode)`).

**Comment by eush77** [comment]
I definitely remember the conversation, must not have foreseen the consequences for this project then.

I feel like option (a) would be confusing, and that option (b) is better in that it is more consistent with the rest of the ecosystem.

We can also drop array-of-nodes form (which is my invention): the only [use](https://github.com/egoist/magi-deprecated/blob/ac16723e712552decf839e7d851f5c1e383df298/src/lib/index.js#L86) I found is in an apparently deprecated project, so that should be no problem.
